//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTOKOC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTOKOCEntities : DbContext
    {
        public OTOKOCEntities()
            : base("name=OTOKOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
        public virtual DbSet<PARCA> PARCA { get; set; }
        public virtual DbSet<SIPARIS> SIPARIS { get; set; }
        public virtual DbSet<MARKA> MARKA { get; set; }
        public virtual DbSet<MODEL> MODEL { get; set; }
        public virtual DbSet<OZELLIK> OZELLIK { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
