//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTOKOC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OZELLIK
    {
        public int ID { get; set; }
        public Nullable<int> MODEL { get; set; }
        public Nullable<int> PARCA { get; set; }
    
        public virtual MODEL MODEL1 { get; set; }
        public virtual PARCA PARCA1 { get; set; }
    }
}
