//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTOKOC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARCA()
        {
            this.SIPARIS = new HashSet<SIPARIS>();
            this.OZELLIK = new HashSet<OZELLIK>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<int> NO { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
        public string FOTOGRAF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARIS> SIPARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OZELLIK> OZELLIK { get; set; }
    }
}
