//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTOKOC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS
    {
        public int ID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<int> TUTAR { get; set; }
        public Nullable<int> KULLANICI { get; set; }
    
        public virtual KULLANICI KULLANICI1 { get; set; }
        public virtual PARCA PARCA { get; set; }
    }
}
